main: me.vasil7112.SleepyFeeling.SleepyFeeling
name: SleepyFeeling
description: SleepyFeeling
version: 1.2.0
author: vasil7112
commands:
   SleepyFeeling:
      description: Displays all commands.
      usage: /<command>