main: me.vasil7112.SleepyFeeling.SleepyFeeling
name: SleepyFeeling
description: SleepyFeeling
version: 1.2.1
author: vasil7112
depend: [Vault, WorldGuard, Essentials]
commands:
   SleepyFeeling:
      description: Displays all commands.
      usage: /<command>